package template

// DefaultCommentTemplate is the embedded default template for PR comments
// This template supports MultiEnvCommentData structure
const DefaultCommentTemplate = `<!-- gitops-kustomz: {{.Service}} - auto-generated comment, please do not remove -->

# 🔍 GitOps Policy Check: {{.Service}}

**Timestamp:** {{.Timestamp.Format "2006-01-02 15:04:05 UTC"}}  
**Base:** ` + "`{{.BaseCommit}}`" + ` → **Head:** ` + "`{{.HeadCommit}}`" + `  
**Environments:** {{range $i, $env := .Environments}}{{if $i}}, {{end}}` + "`{{$env}}`" + `{{end}}

---

## 📊 Manifest Changes

{{if .EnvironmentDiffs}}
{{range .EnvironmentDiffs}}
### {{.Environment}}

{{if .HasChanges}}
**Lines changed:** {{.LineCount}}

<details>
<summary>Click to expand {{.Environment}} diff</summary>

` + "```diff" + `
{{.Content}}
` + "```" + `

</details>
{{else}}
✅ No changes detected.
{{end}}

{{end}}
{{else}}
✅ No changes detected.
{{end}}

---

## 🛡️ Policy Evaluation Results

### Summary

{{range $env, $sum := .MultiEnvPolicyReport.Summary}}
**{{$env}}:** {{$sum.PassedPolicies}}/{{$sum.TotalPolicies}} passed{{if gt $sum.FailedPolicies 0}} | ❌ {{$sum.FailedPolicies}} failed{{end}}{{if gt $sum.ErroredPolicies 0}} | 💥 {{$sum.ErroredPolicies}} errored{{end}}  
{{end}}

### Policy Matrix

| Policy | Enforcement |{{range .MultiEnvPolicyReport.Environments}} {{.}} |{{end}}
|--------|-------------|{{range .MultiEnvPolicyReport.Environments}}--------|{{end}}
{{range $policy := .MultiEnvPolicyReport.Policies}}| {{$policy.Name}} | {{$policy.Level}} |{{range $env := $.MultiEnvPolicyReport.Environments}}{{$result := index $policy.Results $env}} {{if $result}}{{$result.Status}}{{else}}N/A{{end}} |{{end}}
{{end}}

{{range $env, $sum := .MultiEnvPolicyReport.Summary}}
{{if gt $sum.FailedPolicies 0}}
### ⚠️ Failed Policies in {{$env}}

{{range $.MultiEnvPolicyReport.Policies}}
{{$result := index .Results $env}}
{{if and $result (ne $result.Status "PASS")}}
#### {{.Name}}
- **Enforcement:** {{.Level}}
{{if $result.Violations}}- **Violations:**{{range $result.Violations}}
  - {{.}}{{end}}{{end}}
{{if $result.Error}}- **Error:** {{$result.Error}}{{end}}
{{end}}
{{end}}
{{end}}
{{end}}

---

_Generated by [gitops-kustomz](https://github.com/gh-nvat/gitops-kustomz)_
`
