name: GitOps Policy Check

on:
  pull_request:
    paths:
      - 'services/**'  # Adjust to match your manifests path
      - 'policies/**'  # Trigger when policies change too

permissions:
  contents: read
  pull-requests: write  # Required to post comments

env:
  KUSTOMIZE_VERSION: '5.3.0'
  OPA_VERSION: '0.60.0'
  GITOPS_KUSTOMZ_VERSION: 'v0.0.1'  # Pin to specific release version

jobs:
  detect-changes:
    name: Detect Changed Services
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Only need base and head commits

      - name: Detect changed services and environments
        id: set-matrix
        run: |
          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          
          # Extract unique service-environment combinations
          # Assumes structure: services/<service>/environments/<env>/
          SERVICES=$(echo "$CHANGED_FILES" | \
            grep -E '^services/[^/]+/environments/[^/]+/' | \
            sed -E 's|^services/([^/]+)/environments/([^/]+)/.*|\1:\2|' | \
            sort -u)
          
          if [ -z "$SERVICES" ]; then
            echo "No service changes detected"
            echo "matrix={\"include\":[]}" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Build JSON matrix
          MATRIX_JSON=$(echo "$SERVICES" | jq -R -s -c '
            split("\n") | 
            map(select(length > 0)) | 
            map(split(":") | {service: .[0], environment: .[1]}) |
            {include: .}
          ')
          
          echo "Detected changes:"
          echo "$MATRIX_JSON" | jq .
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  policy-check:
    name: Check ${{ matrix.service }} (${{ matrix.environment }})
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.matrix != '{"include":[]}'
    strategy:
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
      fail-fast: false  # Continue checking all services even if one fails
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Only need base and head commits


      - name: Cache tools
        id: cache-tools
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/bin/kustomize
            /usr/local/bin/opa
            ~/go/bin/gitops-kustomz
          key: tools-${{ runner.os }}-kustomize-${{ env.KUSTOMIZE_VERSION }}-opa-${{ env.OPA_VERSION }}-gitops-${{ env.GITOPS_KUSTOMZ_VERSION }}

      - name: Install kustomize
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          curl -sL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${{ env.KUSTOMIZE_VERSION }}/kustomize_v${{ env.KUSTOMIZE_VERSION }}_linux_amd64.tar.gz" | tar xz
          sudo mv kustomize /usr/local/bin/
          kustomize version

      - name: Install OPA
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          curl -L -o opa "https://github.com/open-policy-agent/opa/releases/download/v${{ env.OPA_VERSION }}/opa_linux_amd64_static"
          chmod +x opa
          sudo mv opa /usr/local/bin/
          opa version

      - name: Install gitops-kustomz
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          # Download pre-built binary from GitHub releases
          ARCH=$(uname -m)
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          
          # Map architecture names
          if [ "$ARCH" = "x86_64" ]; then ARCH="amd64"; fi
          if [ "$ARCH" = "aarch64" ]; then ARCH="arm64"; fi
          
          BINARY_NAME="gitops-kustomz-${OS}-${ARCH}"
          DOWNLOAD_URL="https://github.com/gh-nvat/gitops-kustomz/releases/download/${{ env.GITOPS_KUSTOMZ_VERSION }}/${BINARY_NAME}"
          
          echo "Downloading ${BINARY_NAME} from ${DOWNLOAD_URL}"
          curl -sL "${DOWNLOAD_URL}" -o ~/go/bin/gitops-kustomz
          chmod +x ~/go/bin/gitops-kustomz
          ~/go/bin/gitops-kustomz --version

      - name: Add tools to PATH
        run: |
          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run policy check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gitops-kustomz \
            --run-mode github \
            --gh-repo ${{ github.repository }} \
            --gh-pr-number ${{ github.event.pull_request.number }} \
            --service ${{ matrix.service }} \
            --environments ${{ matrix.environment }} \
            --policies-path ./policies \
            --templates-path ./templates
        continue-on-error: true  # Don't fail the job, let the tool determine pass/fail

      - name: Check result
        if: failure()
        run: |
          echo "::error::Policy check failed for ${{ matrix.service }} (${{ matrix.environment }})"
          exit 1

  # Optional: Aggregate results
  policy-check-summary:
    name: Policy Check Summary
    runs-on: ubuntu-latest
    needs: [detect-changes, policy-check]
    if: always()
    steps:
      - name: Check overall status
        run: |
          if [ "${{ needs.policy-check.result }}" == "failure" ]; then
            echo "::error::One or more policy checks failed"
            exit 1
          elif [ "${{ needs.policy-check.result }}" == "success" ]; then
            echo "✅ All policy checks passed"
          else
            echo "ℹ️ No policy checks needed"
          fi

